matrix:
  include:
    - language: python
      python: 3.6
      install:
        - pip install -r neural/requirements.txt
      script:
        - (cd neural/ && python -m unittest discover)

    - language: node_js
      node_js: 8.12.0
      install:
        - npm install
      script:
        - npm test
